{% set name = "hdmf" %}
{% set version = "3.2.1" %}
{% set sha256 = "6a20bd8dbc79839b924facb3a59918d634fcf9410abfe68917da585f6111dacd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python >=3.7
    - h5py >=2.10,<4
    - jsonschema >=2.6.0,<5
    - numpy >=1.16,<1.23
    - pandas >=1.0.5,<2
    - ruamel.yaml >=0.16,<1
    - scipy >=1.1,<2
    - setuptools

test:
  imports:
    - hdmf

about:
  home: https://github.com/hdmf-dev/hdmf
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with hierarchical object data
  description: |
    The Hierarchical Data Modeling Framework, or HDMF is a Python package
    for working with hierarchical data. It provides APIs for specifying data
    models, reading and writing data to different storage backends, and
    representing data with Python object.
  doc_url: http://hdmf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ajtritt
    - rly
    - oruebel
